document.addEventListener("DOMContentLoaded", function() {
    alert("⚠️ PERINGATAN AKUN ANDA SAAT INI SEDANG DALAM PROSES DI  MASUKKAN KE DATABASE MILIK SERVER WEB DAN JIKA BERHASIL DI MASUKKAN DI DALAM DATABASE PIHAK KE TIGA BISA MENCARI DATA PRIBADI ANDA TOLONG KEMBALI ");
});
